In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px   #interactive plots and visualizations
import plotly.io as pio  #Plotly I/O for exporting and displaying  static images 
pio.renderers.default = "svg"  # Scalable Vector Graphics high-quality graphics

In [2]:
dataset=pd.read_csv('Zomato Chennai Listing 2020.csv')

In [3]:
dataset.head(70)

,Zomato URL,Name of Restaurant,Address,Location,Cuisine,Top Dishes,Price for 2,Dining Rating,Dining Rating Count,Delivery Rating,Delivery Rating Count,Features
0,https://www.zomato.com/chennai/yaa-mohaideen-b...,Yaa Mohaideen Briyani,"336 & 338, Main Road, Pallavaram, Chennai",Pallavaram,['Biryani'],"['Bread Halwa', ' Chicken 65', ' Mutton Biryan...",500.0,4.3,1500,4.3,9306,"['Home Delivery', 'Indoor Seating']"
1,https://www.zomato.com/chennai/sukkubhai-biriy...,Sukkubhai Biriyani,"New 14, Old 11/3Q, Railway Station Road, MKN ...",Alandur,"['Biryani', ' North Indian', ' Mughlai', ' Des...","['Beef Biryani', ' Beef Fry', ' Paratha', ' Pa...",1000.0,4.4,3059,4.1,39200,"['Home Delivery', 'Free Parking', 'Table booki..."
2,https://www.zomato.com/chennai/ss-hyderabad-bi...,SS Hyderabad Biryani,"98/339, Arcot Road, Opposite Gokulam Chit Fun...",Kodambakkam,"['Biryani', ' North Indian', ' Chinese', ' Ara...","['Brinjal Curry', ' Tandoori Chicken', ' Chick...",500.0,4.3,1361,4.4,10500,"['Home Delivery', 'Indoor Seating']"
3,https://www.zomato.com/chennai/kfc-perambur,KFC,"10, Periyar Nagar, 70 Feet Road, Near Sheeba ...",Perambur,"['Burger', ' Fast Food', ' Finger Food', ' Bev...",['Zinger Burger'],500.0,4.0,1101,4.0,11200,"['Home Delivery', 'Free Parking', 'Card Upon D..."
4,https://www.zomato.com/chennai/tasty-kitchen-p...,Tasty Kitchen,"135B, SRP Colony, Peravallur, Near Perambur, ...",Perambur,"['Chinese', ' Biryani', ' North Indian', ' Che...","['Mutton Biryani', ' Chicken Rice', ' Tomato R...",450.0,4.2,617,4.1,22400,"['Home Delivery', 'Indoor Seating']"
...,...,...,...,...,...,...,...,...,...,...,...,...
65,https://www.zomato.com/chennai/sree-akshayam-a...,Sree Akshayam,"AJ 6, 4th Avenue, Shanthi Colony, Anna Nagar ...",Anna Nagar East,"['South Indian', ' North Indian', ' Chinese', ...","['Paratha', ' Paneer Tikka', ' Naan', ' Pongal...",700.0,4.3,1225,3.9,12600,"['Breakfast', 'Home Delivery', 'Vegetarian Onl..."
66,https://www.zomato.com/chennai/biriyani-palace...,Biriyani Palace,"116, Bazar Road, Kundrathur, Porur, Chennai",Porur,"['North Indian', ' Chinese', ' Biryani', ' Keb...","['Biryani', ' Tandoori Chicken', ' Bbq Chicken']",600.0,4.0,849,3.4,7318,"['Home Delivery', 'Free Parking', 'Indoor Seat..."
67,https://www.zomato.com/chennai/pumpkin-tales-a...,Pumpkin Tales,"37/20, Bheemanna Garden Street, Alwarpet, Che...",Alwarpet,"['Singaporean', ' American', ' European', ' Co...","['Pumpkin Soup', ' Bibimbap', ' Noodle', ' Che...",1800.0,4.5,768,4.0,245,"['Breakfast', 'Home Delivery', 'Indoor Seating..."
68,https://www.zomato.com/chennai/sandys-chocolat...,Sandy's Chocolate Laboratory,"16, Wallace Garden, 2nd Street, Nungambakkam,...",Nungambakkam,"['Cafe', ' Continental', ' Italian', ' Desserts']","['Tiny Chocolate Cake', ' Hot Chocolate', ' Sa...",1400.0,4.5,2252,4.3,1973,"['Breakfast', 'Home Delivery', 'Free Parking',..."
69,https://www.zomato.com/chennai/hotel-saravana-...,Hotel Saravana Bhavan,"111/141, Near Kandanchavadi Bus Depot, Old Ma...",Perungudi,"['North Indian', ' South Indian', ' Desserts',...","['Filtered Coffee', ' Masala Dosa', ' Thali', ...",550.0,2.7,854,3.7,14500,"['Breakfast', 'Home Delivery', 'Vegetarian Onl..."

In [4]:
dataset.shape

(12032, 12)

In [5]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12032 entries, 0 to 12031
Data columns (total 12 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Zomato URL             12032 non-null  object
 1   Name of Restaurant     12032 non-null  object
 2   Address                12032 non-null  object
 3   Location               12032 non-null  object
 4   Cuisine                12032 non-null  object
 5   Top Dishes             12032 non-null  object
 6   Price for 2            12032 non-null  float64
 7   Dining Rating          6681 non-null   float64
 8   Dining Rating Count    11812 non-null  object
 9   Delivery Rating        6181 non-null   float64
 10  Delivery Rating Count  11812 non-null  object
 11  Features               12032 non-null  object
dtypes: float64(3), object(9)
memory usage: 1.1+ MB

In [6]:
dataset.describe()

        Price for 2  Dining Rating  Delivery Rating
count  12032.000000    6681.000000      6181.000000
mean     397.611370       3.387756         3.805290
std      332.045938       0.558181         0.374213
min       40.000000       0.300000         0.300000
25%      200.000000       3.100000         3.600000
50%      300.000000       3.500000         3.900000
75%      450.000000       3.800000         4.000000
max     5000.000000       4.900000         4.700000

In [7]:
dataset.isna().sum()

Zomato URL                  0
Name of Restaurant          0
Address                     0
Location                    0
Cuisine                     0
Top Dishes                  0
Price for 2                 0
Dining Rating            5351
Dining Rating Count       220
Delivery Rating          5851
Delivery Rating Count     220
Features                    0
dtype: int64

In [8]:
#Replacing the other null records with NA
dataset.fillna('0', inplace=True)

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_20264\3874851706.py:2: FutureWarning:

Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.

In [9]:
# Confirming all the null records are correct
dataset.isnull().sum()

Zomato URL               0
Name of Restaurant       0
Address                  0
Location                 0
Cuisine                  0
Top Dishes               0
Price for 2              0
Dining Rating            0
Dining Rating Count      0
Delivery Rating          0
Delivery Rating Count    0
Features                 0
dtype: int64

In [10]:
dataset.dtypes

Zomato URL                object
Name of Restaurant        object
Address                   object
Location                  object
Cuisine                   object
Top Dishes                object
Price for 2              float64
Dining Rating             object
Dining Rating Count       object
Delivery Rating           object
Delivery Rating Count     object
Features                  object
dtype: object

In [11]:
# Checking for text values in the column before converting it to numeric datatype
dataset['Dining Rating Count'].value_counts()

Dining Rating Count
Does not offer Dining        2603
Not enough Dining Reviews    2528
4                             339
5                             271
6                             248
                             ...
877                             1
897                             1
872                             1
1197                            1
224                             1
Name: count, Length: 793, dtype: int64

In [12]:
# Replacing the text values with '0'
dataset['Dining Rating Count'].replace(to_replace=['Does not offer Dining','Not enough Dining Reviews'], value='0', inplace=True)

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_20264\3524512671.py:2: FutureWarning:

A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.

In [13]:
dataset['Delivery Rating Count'].value_counts()

Delivery Rating Count
Not enough Delivery Reviews    3379
Does not offer Delivery        2252
0                               239
27                               34
40                               30
                               ...
7705                              1
6374                              1
3677                              1
588                               1
1617                              1
Name: count, Length: 2281, dtype: int64

In [14]:
dataset['Delivery Rating Count'].replace(to_replace=['Not enough Delivery Reviews','Does not offer Delivery'], value='0', inplace=True)

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_20264\2781772949.py:1: FutureWarning:

A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.

In [15]:
# Changing Data Type of the numerical columns
dataset['Dining Rating'] = dataset['Dining Rating'].astype('float64')
dataset['Dining Rating Count'] = dataset['Dining Rating Count'].astype('int64')
dataset['Delivery Rating'] = dataset['Delivery Rating'].astype('float64')
dataset['Delivery Rating Count'] = dataset['Delivery Rating Count'].astype('int64')

In [16]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12032 entries, 0 to 12031
Data columns (total 12 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Zomato URL             12032 non-null  object
 1   Name of Restaurant     12032 non-null  object
 2   Address                12032 non-null  object
 3   Location               12032 non-null  object
 4   Cuisine                12032 non-null  object
 5   Top Dishes             12032 non-null  object
 6   Price for 2            12032 non-null  float64
 7   Dining Rating          12032 non-null  float64
 8   Dining Rating Count    12032 non-null  int64
 9   Delivery Rating        12032 non-null  float64
 10  Delivery Rating Count  12032 non-null  int64
 11  Features               12032 non-null  object
dtypes: float64(3), int64(2), object(7)
memory usage: 1.1+ MB

In [17]:
dataset.dtypes

Zomato URL                object
Name of Restaurant        object
Address                   object
Location                  object
Cuisine                   object
Top Dishes                object
Price for 2              float64
Dining Rating            float64
Dining Rating Count        int64
Delivery Rating          float64
Delivery Rating Count      int64
Features                  object
dtype: object

In [18]:
dataset.head(50)

,Zomato URL,Name of Restaurant,Address,Location,Cuisine,Top Dishes,Price for 2,Dining Rating,Dining Rating Count,Delivery Rating,Delivery Rating Count,Features
0,https://www.zomato.com/chennai/yaa-mohaideen-b...,Yaa Mohaideen Briyani,"336 & 338, Main Road, Pallavaram, Chennai",Pallavaram,['Biryani'],"['Bread Halwa', ' Chicken 65', ' Mutton Biryan...",500.0,4.3,1500,4.3,9306,"['Home Delivery', 'Indoor Seating']"
1,https://www.zomato.com/chennai/sukkubhai-biriy...,Sukkubhai Biriyani,"New 14, Old 11/3Q, Railway Station Road, MKN ...",Alandur,"['Biryani', ' North Indian', ' Mughlai', ' Des...","['Beef Biryani', ' Beef Fry', ' Paratha', ' Pa...",1000.0,4.4,3059,4.1,39200,"['Home Delivery', 'Free Parking', 'Table booki..."
2,https://www.zomato.com/chennai/ss-hyderabad-bi...,SS Hyderabad Biryani,"98/339, Arcot Road, Opposite Gokulam Chit Fun...",Kodambakkam,"['Biryani', ' North Indian', ' Chinese', ' Ara...","['Brinjal Curry', ' Tandoori Chicken', ' Chick...",500.0,4.3,1361,4.4,10500,"['Home Delivery', 'Indoor Seating']"
3,https://www.zomato.com/chennai/kfc-perambur,KFC,"10, Periyar Nagar, 70 Feet Road, Near Sheeba ...",Perambur,"['Burger', ' Fast Food', ' Finger Food', ' Bev...",['Zinger Burger'],500.0,4.0,1101,4.0,11200,"['Home Delivery', 'Free Parking', 'Card Upon D..."
4,https://www.zomato.com/chennai/tasty-kitchen-p...,Tasty Kitchen,"135B, SRP Colony, Peravallur, Near Perambur, ...",Perambur,"['Chinese', ' Biryani', ' North Indian', ' Che...","['Mutton Biryani', ' Chicken Rice', ' Tomato R...",450.0,4.2,617,4.1,22400,"['Home Delivery', 'Indoor Seating']"
5,https://www.zomato.com/chennai/dine-n-fun-meda...,Dine N Fun,"Opposite Forest Office, Tambaram Main Road, S...",Medavakkam,"['South Indian', ' North Indian', ' Chinese']","['Chicken Grill', ' Shawarma', ' Naan', ' Chic...",450.0,4.1,567,3.8,24700,"['Home Delivery', 'Indoor Seating']"
6,https://www.zomato.com/chennai/bai-veetu-kalya...,Bai Veetu Kalyanam,"1/187, Thalambur Road, Navallur, Chennai",Navallur,['Biryani'],"['Bread Halwa', ' Mutton Biryani', ' Brinjal G...",350.0,0.0,0,4.3,1061,['Home Delivery']
7,https://www.zomato.com/chennai/cafe-arabica-an...,Cafe Arabica,"3, E Block, 3rd Avenue, Anna Nagar East, Chennai",Anna Nagar East,"['Cafe', ' Fast Food']","['Burgers', ' Pasta', ' Sandwich', ' Strawberr...",800.0,4.3,668,4.3,4320,"['Breakfast', 'Home Delivery', 'Indoor Seating..."
8,https://www.zomato.com/chennai/savoury-sea-she...,Savoury Sea Shell,"3, E Block, 3rd Avenue, Anna Nagar East, Chennai",Anna Nagar East,"['Arabian', ' Chinese', ' North Indian', ' Leb...","['Shawarma', ' Chicken Grill', ' Brownie', ' S...",1400.0,4.2,2564,4.1,21700,"['Home Delivery', 'Indoor Seating', 'Card Upon..."
9,https://www.zomato.com/chennai/sangeetha-veg-r...,Sangeetha Veg Restaurant,"102/82, GN Chetty Road, T. Nagar, Chennai",T. Nagar,"['South Indian', ' North Indian', ' Chinese', ...","['Filtered Coffee', ' Chaat', ' Faluda', ' Mas...",800.0,4.4,1578,4.2,39600,"['Breakfast', 'Home Delivery', 'Vegetarian Onl..."
10,https://www.zomato.com/chennai/mcdonalds-velac...,McDonald's,"330/12, Grand Arcade, Dr Seetharaman Nagar, V...",Velachery,"['Burger', ' Fast Food']","['Burgers', ' Peri Peri Fries', ' French Fries...",500.0,3.9,743,3.9,6226,"['Breakfast', 'Home Delivery', 'Indoor Seating']"
11,https://www.zomato.com/chennai/kovai-alankar-v...,Kovai Alankar Vilas,"AC 3, 2nd Avenue, Anna Nagar East, Chennai .",Anna Nagar East,['South Indian'],"['Elaneer Payasam', ' Paratha', ' Mutton Chukk...",700.0,4.4,961,3.6,7591,"['Home Delivery', 'Free Parking', 'Indoor Seat..."
12,https://www.zomato.com/chennai/hotel-al-buhari...,Hotel Al Buhari,"81, Opposite AVM Theater, Arcot Road, Vadapal...",Vadapalani,"['Chinese', ' Chettinad']","['Shawarma', ' Fried Rice Chicken', ' Biryani']",350.0,4.0,982,3.8,22400,"['Home Delivery', 'Indoor Seating']"
13,https://www.zomato.com/chennai/dindigul-thalap...,Dindigul Thalappakatti,"New 21-A, Arcot Road, Porur, Chennai",Porur,"['South Indian', ' Biryani', ' Chinese', ' Nor...","['Mutton Biryani', ' Faluda', ' Barbeque Chick...",900.0,4.3,770,4.0,7670,"['Home Delivery', 'Indoor Seating', 'Table res..."
14,https://www.zomato.com/chennai/hotel-paramount...,Hotel Paramount,"12/5, Ormes Road, Kilpauk, Chennai",Kilpauk,"['North Indian', ' Chinese', ' Seafood', ' Sou...","['Biryani', ' Butter Chicken', ' Tandoori Chic...",500.0,4.3,1266,4.2,17700,"['Breakfast', 'Home Delivery', 'Indoor Seating..."
15,https://www.zomato.com/chennai/welcome-hotel-p...,Welcome Hotel,"112/241, Purasawalkam High Road, Purasavakkam...",Purasavakkam,"['South Indian', ' Desserts', ' Beverages']","['Pongal', ' Podi Dosa', ' Idli Sambar', ' Vad...",300.0,4.5,1094,0.0,0,"['Breakfast', 'Vegetarian Only', 'Indoor Seati..."
16,https://www.zomato.com/chennai/arab-street-ash...,Arab Street,"101, 4th Avenue, Ward 133, Ashok Nagar, Chennai",Ashok Nagar,"['Arabian', ' Biryani', ' Chinese', ' North In...","['Shawarma', ' Biryani', ' Chicken Grill', ' K...",800.0,4.1,1363,3.8,6228,"['Home Delivery', 'Valet Parking Available', '..."
17,https://www.zomato.com/chennai/abids-chetpet,Abid's,"21, Spurtank Road, Chetpet, Chennai",Chetpet,"['Seafood', ' Biryani', ' Hyderabadi', ' Arabi...","['Haleem', ' Hyderabadi Dum Biryani', ' Brinja...",1200.0,4.2,742,4.1,3020,"['Home Delivery', 'Valet Parking Available', '..."
18,https://www.zomato.com/chennai/wire-room-bar-k...,Wire Room Bar & Kitchen,"142, Phoenix Marketcity, New NGO Colony, Vela...","Phoenix Market City, Velachery","['Continental', ' Asian']","['Cocktails', ' Salad', ' Beer', ' Tikka', ' P...",2000.0,4.1,354,0.0,0,"['Full Bar Available', 'Mall Parking', 'Dance ..."
19,https://www.zomato.com/chennai/malabar-biriyan...,Malabar Biriyani Center,"132/89, Nelson Manickam Road, Mehtha Nagar, A...",Aminijikarai,"['Kerala', ' Chinese', ' North Indian', ' Biry...","['Chicken Grill', ' Paratha', ' Malabari Birya...",450.0,4.1,660,3.9,12600,"['Home Delivery', 'Indoor Seating']"
20,https://www.zomato.com/chennai/velidis-ramapuram,Velidis,"3/88, Mount Poonamallee Road, Ramapuram, Chennai",Ramapuram,"['Andhra', ' Biryani', ' North Indian']","['Chicken Guntur', ' Hyderabadi Biryani', ' Gu...",500.0,4.2,802,4.1,10600,"['Home Delivery', 'Free Parking', 'Indoor Seat..."
21,https://www.zomato.com/chennai/mami-tiffen-sta...,Mami Tiffen Stall,"7, Pitchupillai Street, Near Kapaleeshwarar T...",Mylapore,"['South Indian', ' North Indian', ' Chinese', ...","['Vada Curry', ' Filtered Coffee', ' Pongal', ...",400.0,4.3,578,3.9,14700,"['Breakfast', 'Home Delivery', 'Free Parking',..."
22,https://www.zomato.com/chennai/supriya-andhra-...,Supriya Andhra Restaurant,"5/349, Rajiv Gandhi Salai, OMR, Thuraipakkam,...",Thuraipakkam,"['Biryani', ' North Indian', ' Chinese']","['Biryani', ' Raita']",650.0,4.2,1992,3.8,50100,"['Home Delivery', 'Free Parking', 'Indoor Seat..."
23,https://www.zomato.com/chennai/bff-2-0-ra-puram,BFF 2.0,"80/29, 2nd Main Road, RA Puram, Chennai",RA Puram,"['North Indian', ' Continental', ' Italian']","['Crispy Chicken', ' Cocktails', ' Pizza', ' N...",1500.0,4.2,464,0.0,0,"['Full Bar Available', 'Indoor Seating', 'Nigh..."
24,https://www.zomato.com/chennai/eating-circles-...,Eating Circles,"6, CP Ramaswamy Road, Alwarpet, Chennai",Alwarpet,['South Indian'],"['Rose Milk', ' Neer Dosa', ' Thatte Idli', ' ...",250.0,4.7,782,4.2,2744,"['Breakfast', 'Home Delivery', 'Vegetarian Onl..."
25,https://www.zomato.com/chennai/salem-rr-briyan...,Salem RR Briyani Unavagam,"166, 100 Feet Road, Ganapathi Nagar, Velacher...",Velachery,"['Biryani', ' Chinese', ' North Indian', ' Sea...","['Chicken 65', ' Mutton Biryani', ' Tandoori C...",550.0,4.2,1180,4.0,1717,"['Home Delivery', 'Indoor Seating', 'Catering ..."
26,https://www.zomato.com/chennai/v4-midnight-dha...,V4 Midnight Dhabba,"22, Nolambur Service Road, Opposite KG Signat...",Mogappair,"['North Indian', ' Mughlai']","['Egg Noodles', ' Punjabi Chicken', ' Cream Ch...",550.0,4.3,1139,3.9,10100,"['Home Delivery', 'Indoor Seating', 'Table boo..."
27,https://www.zomato.com/chennai/bakya-veg-resta...,Bakya Veg Restaurant,"20, Jaishankar Street, Near Ayodhya Mandapam,...",West Mambalam,"['South Indian', ' North Indian', ' Chinese']","['Panneer Butter Masala', ' Noodle', ' Chaat',...",400.0,4.2,457,4.0,19400,"['Breakfast', 'Home Delivery', 'Vegetarian Onl..."
28,https://www.zomato.com/chennai/midnight-madnes...,Midnight Madness,"1\/1, F-3, 1st Floor, Sindhuja Complex, 29th ...",Adyar,['Italian'],"['Pasta', ' Noodle', ' Peri Peri Chicken Pizza']",450.0,4.1,625,3.3,10300,"['Home Delivery', 'Indoor Seating']"
29,https://www.zomato.com/chennai/hotel-crescent-...,Hotel Crescent,"309, Valluvar Kottam High Road, Nungambakkam,...",Nungambakkam,"['Chettinad', ' Chinese', ' North Indian', ' K...","['Chicken Grill', ' Shawarma', ' Paratha', ' F...",500.0,4.3,1030,4.2,2731,"['Home Delivery', 'Indoor Seating']"
30,https://www.zomato.com/chennai/zaitoon-royapettah,Zaitoon,"35, Woods Road., Royapettah, Chennai",Royapettah,"['North Indian', ' Arabian', ' Chinese']","['Shawarma', ' Bbq Chicken', ' Biryani', ' Sal...",900.0,4.1,1118,4.1,2895,"['Home Delivery', 'Serves Halal', 'Free Parkin..."
31,https://www.zomato.com/chennai/nithya-amirtham...,Nithya Amirtham,"39, North Mada Street, Near Kapaleeswarar Tem...",Mylapore,"['South Indian', ' North Indian', ' Chinese']","['Tomato Soup', ' Filtered Coffee', ' Thali', ...",500.0,4.2,403,4.3,11100,"['Breakfast', 'Home Delivery', 'Vegetarian Onl..."
32,https://www.zomato.com/chennai/shri-balaajee-b...,Shri Balaajee Bhavan,"412/07, Thoraipakam Road Over Bridge, Chromep...",Chromepet,"['South Indian', ' North Indian']","['Filtered Coffee', ' Panneer Butter Masala', ...",300.0,4.3,602,4.0,1868,"['Breakfast', 'Home Delivery', 'Vegetarian Onl..."
33,https://www.zomato.com/chennai/kakada-ramprasa...,Kakada Ramprasad,"Ormes Road, Sylvan Lodge Colony, Kilpauk, Che...",Kilpauk,"['Mithai', ' Street Food', ' North Indian']","['Badam Milk', ' Chaat', ' Pav Bhaji', ' Jaleb...",450.0,4.3,455,4.3,4253,"['Breakfast', 'Home Delivery', 'Vegetarian Onl..."
34,https://www.zomato.com/chennai/rasavid-1-velac...,Rasavid,"55 C, Velachery By-Pass Road, Sankaran Avenue...",Velachery,"['Andhra', ' Hyderabadi']","['Naan', ' Biryani', ' Bbq Fish', ' Tomato Sou...",800.0,3.9,350,3.4,3708,"['Home Delivery', 'Indoor Seating', 'Buffet']"
35,https://www.zomato.com/chennai/buhari-chromepet,Buhari,"Near Vetri Theatre, Chromepet, Chennai",Chromepet,"['Biryani', ' Arabian', ' North Indian', ' Chi...","['Biryani', ' Chicken 65', ' Sea Food', ' Tea'...",800.0,3.5,646,3.8,1552,"['Home Delivery', 'Indoor Seating', 'Catering ..."
36,https://www.zomato.com/chennai/dominos-pizza-k...,Domino's Pizza,"2, Ground Floor, Valavan Nagar, Kolathur, Che...",Kolathur,"['Pizza', ' Fast Food']","['Mexican Tacos', ' Peppy Paneer', ' Farmhouse...",400.0,4.0,429,4.1,5297,"['Home Delivery', 'Indoor Seating', 'Catering ..."
37,https://www.zomato.com/chennai/shree-mithai-ch...,Shree Mithai,"18, Dr TV Road, Chetpet, Chennai",Chetpet,"['Mithai', ' Street Food', ' Fast Food']","['Chaat', ' Badam Milk', ' Pav Bhaji', ' Panip...",300.0,4.6,1085,4.4,18600,"['Breakfast', 'Home Delivery', 'Vegetarian Onl..."
38,https://www.zomato.com/chennai/new-andhra-meal...,New Andhra Meals Hotel,"6, Arcot Road, Valasaravakkam, Chennai",Valasaravakkam,"['Andhra', ' Chinese', ' South Indian', ' Nort...","['Paruppu Podi', ' Gongura Chicken', ' Panneer...",600.0,3.9,704,4.2,1457,"['Home Delivery', 'Indoor Seating', 'Table boo..."
39,https://www.zomato.com/chennai/punjabi-nation-...,Punjabi Nation,"15, GST Road, Guindy, Chennai",Guindy,"['North Indian', ' Chinese']","['Lassi', ' Roti', ' Naan', ' Butter Chicken',...",700.0,4.0,712,4.1,13600,"['Home Delivery', 'Indoor Seating']"
40,https://www.zomato.com/chennai/krishnas-dosa-k...,Krishna's Dosa Kadai,"40, Nolambur, Phase - 1, Mogappair, Chennai",Mogappair,"['South Indian', ' North Indian', ' Andhra', '...","['Pizza Dosa', ' Butter Naan', ' Coffee', ' Ch...",350.0,4.2,692,4.1,34600,"['Breakfast', 'Home Delivery', 'Vegetarian Onl..."
41,https://www.zomato.com/chennai/al-sham-1-potheri,Al Sham,"1, Pillayar Koil Street, Near SRM University,...",Potheri,"['Chinese', ' North Indian', ' Kerala']","['Biryani', ' Chicken Grill', ' Tandoori Chick...",750.0,3.9,601,3.9,17500,"['Home Delivery', 'Table booking recommended',..."
42,https://www.zomato.com/chennai/orange-wok-nung...,Orange Wok,"11, 1st Floor, Khader Nawaz Khan Road, Nungam...",Nungambakkam,"['Malaysian', ' Asian', ' Chinese']","['Laksa', ' Dragon Chicken', ' Khau Suey', ' M...",1000.0,4.2,774,4.0,8705,"['Home Delivery', 'Free Parking', 'Indoor Seat..."
43,https://www.zomato.com/chennai/ghuma-ghumalu-n...,Ghuma Ghumalu,"1/398, Rajiv Gandhi Salai, OMR, Navalur, Chennai",Navallur,"['Chinese', ' South Indian', ' Biryani', ' And...","['Hyderabadi Biryani', ' Chicken 65', ' Chicke...",500.0,4.2,1059,3.6,5961,"['Home Delivery', 'Indoor Seating', 'Table res..."
44,https://www.zomato.com/chennai/kps-ambur-biriy...,KPS Ambur Biriyani,"6/20, Venugopal Street, Mogappair, Chennai",Mogappair,['Biryani'],"['Tandoori Chicken', ' Fried Rice Chicken', ' ...",250.0,3.6,409,3.7,11300,"['Home Delivery', 'Indoor Seating']"
45,https://www.zomato.com/chennai/pedrenos-mylapore,Pedreno's,"113/114, PS Sivaswami Salai, Mylapore, Chennai",Mylapore,"['Pizza', ' American', ' Italian']","['Pizza', ' Gelato', ' Pasta', ' Coffee', ' St...",1200.0,4.3,946,4.0,787,"['Home Delivery', 'Desserts and Bakes', 'Live ..."
46,https://www.zomato.com/chennai/madras-biryani-...,Madras Biryani,"105, EH Road, Sharma Nagar, Vyasarpadi, Peram...",Perambur,"['Biryani', ' Mughlai', ' Fast Food', ' South ...","['Egg Biryani', ' Chicken 65', ' Prawn', ' Fri...",400.0,4.0,559,3.8,15600,"['Home Delivery', 'Indoor Seating', 'Table Res..."
47,https://www.zomato.com/chennai/palmshore-egmore,Palmshore,"99/59, Pantheon Road, Opposite Museum, Egmore...",Egmore,"['North Indian', ' Chinese', ' Arabian', ' BBQ...","['Mutton Mandi', ' Fish', ' Brownie', ' Sea Fo...",1000.0,4.4,2162,4.0,9721,"['Home Delivery', 'Indoor Seating', 'Table boo..."
48,https://www.zomato.com/chennai/hotel-sri-vaira...,Hotel Sri Vairam,"5/24, Karambakkam, Porur, Chennai",Porur,"['Biryani', ' South Indian', ' Chinese', ' Nor...","['Paratha', ' Biryani', ' Mutton Chukka', ' Ch...",300.0,4.0,523,3.8,14700,"['Home Delivery', 'Indoor Seating', 'Free Park..."
49,https://www.zomato.com/chennai/sea-emperor-mad...,Sea Emperor,"11,12 & 13, Velachery Main Road, Ram Nagar, M...",Madipakkam,"['Chinese', ' Arabian', ' North Indian', ' Sea...","['Chicken Grill', ' Shawarma', ' Bbq Chicken',...",900.0,3.8,602,3.9,6855,"['Home Delivery', 'Indoor Seating', 'Catering ..."

In [19]:
dataset.drop('Zomato URL', axis=1, inplace=True)

In [20]:
dataset

,Name of Restaurant,Address,Location,Cuisine,Top Dishes,Price for 2,Dining Rating,Dining Rating Count,Delivery Rating,Delivery Rating Count,Features
0,Yaa Mohaideen Briyani,"336 & 338, Main Road, Pallavaram, Chennai",Pallavaram,['Biryani'],"['Bread Halwa', ' Chicken 65', ' Mutton Biryan...",500.0,4.3,1500,4.3,9306,"['Home Delivery', 'Indoor Seating']"
1,Sukkubhai Biriyani,"New 14, Old 11/3Q, Railway Station Road, MKN ...",Alandur,"['Biryani', ' North Indian', ' Mughlai', ' Des...","['Beef Biryani', ' Beef Fry', ' Paratha', ' Pa...",1000.0,4.4,3059,4.1,39200,"['Home Delivery', 'Free Parking', 'Table booki..."
2,SS Hyderabad Biryani,"98/339, Arcot Road, Opposite Gokulam Chit Fun...",Kodambakkam,"['Biryani', ' North Indian', ' Chinese', ' Ara...","['Brinjal Curry', ' Tandoori Chicken', ' Chick...",500.0,4.3,1361,4.4,10500,"['Home Delivery', 'Indoor Seating']"
3,KFC,"10, Periyar Nagar, 70 Feet Road, Near Sheeba ...",Perambur,"['Burger', ' Fast Food', ' Finger Food', ' Bev...",['Zinger Burger'],500.0,4.0,1101,4.0,11200,"['Home Delivery', 'Free Parking', 'Card Upon D..."
4,Tasty Kitchen,"135B, SRP Colony, Peravallur, Near Perambur, ...",Perambur,"['Chinese', ' Biryani', ' North Indian', ' Che...","['Mutton Biryani', ' Chicken Rice', ' Tomato R...",450.0,4.2,617,4.1,22400,"['Home Delivery', 'Indoor Seating']"
...,...,...,...,...,...,...,...,...,...,...,...
12027,CK's Sandwiches,Delivery Only,Porur,['Sandwich'],Invalid,350.0,0.0,0,0.0,0,"['Breakfast', 'Delivery Only']"
12028,CK's Sandwiches,Delivery Only,Kolathur,['Sandwich'],Invalid,350.0,0.0,0,0.0,0,"['Breakfast', 'Delivery Only']"
12029,CK's Sandwiches,Delivery Only,Anna Nagar East,['Sandwich'],Invalid,350.0,0.0,0,0.0,0,"['Breakfast', 'Delivery Only']"
12030,CK's Sandwiches,Delivery Only,Ramapuram,['Sandwich'],Invalid,350.0,0.0,0,0.0,0,"['Breakfast', 'Delivery Only']"
12031,CK's Sandwiches,Delivery Only,Sholinganallur,['Sandwich'],Invalid,350.0,0.0,0,0.0,0,"['Breakfast', 'Delivery Only']"

In [21]:
dataset = dataset.drop_duplicates()

In [22]:
zomato_chndataset = dataset.copy()

In [23]:
zomato_chndataset.head(50)

,Name of Restaurant,Address,Location,Cuisine,Top Dishes,Price for 2,Dining Rating,Dining Rating Count,Delivery Rating,Delivery Rating Count,Features
0,Yaa Mohaideen Briyani,"336 & 338, Main Road, Pallavaram, Chennai",Pallavaram,['Biryani'],"['Bread Halwa', ' Chicken 65', ' Mutton Biryan...",500.0,4.3,1500,4.3,9306,"['Home Delivery', 'Indoor Seating']"
1,Sukkubhai Biriyani,"New 14, Old 11/3Q, Railway Station Road, MKN ...",Alandur,"['Biryani', ' North Indian', ' Mughlai', ' Des...","['Beef Biryani', ' Beef Fry', ' Paratha', ' Pa...",1000.0,4.4,3059,4.1,39200,"['Home Delivery', 'Free Parking', 'Table booki..."
2,SS Hyderabad Biryani,"98/339, Arcot Road, Opposite Gokulam Chit Fun...",Kodambakkam,"['Biryani', ' North Indian', ' Chinese', ' Ara...","['Brinjal Curry', ' Tandoori Chicken', ' Chick...",500.0,4.3,1361,4.4,10500,"['Home Delivery', 'Indoor Seating']"
3,KFC,"10, Periyar Nagar, 70 Feet Road, Near Sheeba ...",Perambur,"['Burger', ' Fast Food', ' Finger Food', ' Bev...",['Zinger Burger'],500.0,4.0,1101,4.0,11200,"['Home Delivery', 'Free Parking', 'Card Upon D..."
4,Tasty Kitchen,"135B, SRP Colony, Peravallur, Near Perambur, ...",Perambur,"['Chinese', ' Biryani', ' North Indian', ' Che...","['Mutton Biryani', ' Chicken Rice', ' Tomato R...",450.0,4.2,617,4.1,22400,"['Home Delivery', 'Indoor Seating']"
5,Dine N Fun,"Opposite Forest Office, Tambaram Main Road, S...",Medavakkam,"['South Indian', ' North Indian', ' Chinese']","['Chicken Grill', ' Shawarma', ' Naan', ' Chic...",450.0,4.1,567,3.8,24700,"['Home Delivery', 'Indoor Seating']"
6,Bai Veetu Kalyanam,"1/187, Thalambur Road, Navallur, Chennai",Navallur,['Biryani'],"['Bread Halwa', ' Mutton Biryani', ' Brinjal G...",350.0,0.0,0,4.3,1061,['Home Delivery']
7,Cafe Arabica,"3, E Block, 3rd Avenue, Anna Nagar East, Chennai",Anna Nagar East,"['Cafe', ' Fast Food']","['Burgers', ' Pasta', ' Sandwich', ' Strawberr...",800.0,4.3,668,4.3,4320,"['Breakfast', 'Home Delivery', 'Indoor Seating..."
8,Savoury Sea Shell,"3, E Block, 3rd Avenue, Anna Nagar East, Chennai",Anna Nagar East,"['Arabian', ' Chinese', ' North Indian', ' Leb...","['Shawarma', ' Chicken Grill', ' Brownie', ' S...",1400.0,4.2,2564,4.1,21700,"['Home Delivery', 'Indoor Seating', 'Card Upon..."
9,Sangeetha Veg Restaurant,"102/82, GN Chetty Road, T. Nagar, Chennai",T. Nagar,"['South Indian', ' North Indian', ' Chinese', ...","['Filtered Coffee', ' Chaat', ' Faluda', ' Mas...",800.0,4.4,1578,4.2,39600,"['Breakfast', 'Home Delivery', 'Vegetarian Onl..."
10,McDonald's,"330/12, Grand Arcade, Dr Seetharaman Nagar, V...",Velachery,"['Burger', ' Fast Food']","['Burgers', ' Peri Peri Fries', ' French Fries...",500.0,3.9,743,3.9,6226,"['Breakfast', 'Home Delivery', 'Indoor Seating']"
11,Kovai Alankar Vilas,"AC 3, 2nd Avenue, Anna Nagar East, Chennai .",Anna Nagar East,['South Indian'],"['Elaneer Payasam', ' Paratha', ' Mutton Chukk...",700.0,4.4,961,3.6,7591,"['Home Delivery', 'Free Parking', 'Indoor Seat..."
12,Hotel Al Buhari,"81, Opposite AVM Theater, Arcot Road, Vadapal...",Vadapalani,"['Chinese', ' Chettinad']","['Shawarma', ' Fried Rice Chicken', ' Biryani']",350.0,4.0,982,3.8,22400,"['Home Delivery', 'Indoor Seating']"
13,Dindigul Thalappakatti,"New 21-A, Arcot Road, Porur, Chennai",Porur,"['South Indian', ' Biryani', ' Chinese', ' Nor...","['Mutton Biryani', ' Faluda', ' Barbeque Chick...",900.0,4.3,770,4.0,7670,"['Home Delivery', 'Indoor Seating', 'Table res..."
14,Hotel Paramount,"12/5, Ormes Road, Kilpauk, Chennai",Kilpauk,"['North Indian', ' Chinese', ' Seafood', ' Sou...","['Biryani', ' Butter Chicken', ' Tandoori Chic...",500.0,4.3,1266,4.2,17700,"['Breakfast', 'Home Delivery', 'Indoor Seating..."
15,Welcome Hotel,"112/241, Purasawalkam High Road, Purasavakkam...",Purasavakkam,"['South Indian', ' Desserts', ' Beverages']","['Pongal', ' Podi Dosa', ' Idli Sambar', ' Vad...",300.0,4.5,1094,0.0,0,"['Breakfast', 'Vegetarian Only', 'Indoor Seati..."
16,Arab Street,"101, 4th Avenue, Ward 133, Ashok Nagar, Chennai",Ashok Nagar,"['Arabian', ' Biryani', ' Chinese', ' North In...","['Shawarma', ' Biryani', ' Chicken Grill', ' K...",800.0,4.1,1363,3.8,6228,"['Home Delivery', 'Valet Parking Available', '..."
17,Abid's,"21, Spurtank Road, Chetpet, Chennai",Chetpet,"['Seafood', ' Biryani', ' Hyderabadi', ' Arabi...","['Haleem', ' Hyderabadi Dum Biryani', ' Brinja...",1200.0,4.2,742,4.1,3020,"['Home Delivery', 'Valet Parking Available', '..."
18,Wire Room Bar & Kitchen,"142, Phoenix Marketcity, New NGO Colony, Vela...","Phoenix Market City, Velachery","['Continental', ' Asian']","['Cocktails', ' Salad', ' Beer', ' Tikka', ' P...",2000.0,4.1,354,0.0,0,"['Full Bar Available', 'Mall Parking', 'Dance ..."
19,Malabar Biriyani Center,"132/89, Nelson Manickam Road, Mehtha Nagar, A...",Aminijikarai,"['Kerala', ' Chinese', ' North Indian', ' Biry...","['Chicken Grill', ' Paratha', ' Malabari Birya...",450.0,4.1,660,3.9,12600,"['Home Delivery', 'Indoor Seating']"
20,Velidis,"3/88, Mount Poonamallee Road, Ramapuram, Chennai",Ramapuram,"['Andhra', ' Biryani', ' North Indian']","['Chicken Guntur', ' Hyderabadi Biryani', ' Gu...",500.0,4.2,802,4.1,10600,"['Home Delivery', 'Free Parking', 'Indoor Seat..."
21,Mami Tiffen Stall,"7, Pitchupillai Street, Near Kapaleeshwarar T...",Mylapore,"['South Indian', ' North Indian', ' Chinese', ...","['Vada Curry', ' Filtered Coffee', ' Pongal', ...",400.0,4.3,578,3.9,14700,"['Breakfast', 'Home Delivery', 'Free Parking',..."
22,Supriya Andhra Restaurant,"5/349, Rajiv Gandhi Salai, OMR, Thuraipakkam,...",Thuraipakkam,"['Biryani', ' North Indian', ' Chinese']","['Biryani', ' Raita']",650.0,4.2,1992,3.8,50100,"['Home Delivery', 'Free Parking', 'Indoor Seat..."
23,BFF 2.0,"80/29, 2nd Main Road, RA Puram, Chennai",RA Puram,"['North Indian', ' Continental', ' Italian']","['Crispy Chicken', ' Cocktails', ' Pizza', ' N...",1500.0,4.2,464,0.0,0,"['Full Bar Available', 'Indoor Seating', 'Nigh..."
24,Eating Circles,"6, CP Ramaswamy Road, Alwarpet, Chennai",Alwarpet,['South Indian'],"['Rose Milk', ' Neer Dosa', ' Thatte Idli', ' ...",250.0,4.7,782,4.2,2744,"['Breakfast', 'Home Delivery', 'Vegetarian Onl..."
25,Salem RR Briyani Unavagam,"166, 100 Feet Road, Ganapathi Nagar, Velacher...",Velachery,"['Biryani', ' Chinese', ' North Indian', ' Sea...","['Chicken 65', ' Mutton Biryani', ' Tandoori C...",550.0,4.2,1180,4.0,1717,"['Home Delivery', 'Indoor Seating', 'Catering ..."
26,V4 Midnight Dhabba,"22, Nolambur Service Road, Opposite KG Signat...",Mogappair,"['North Indian', ' Mughlai']","['Egg Noodles', ' Punjabi Chicken', ' Cream Ch...",550.0,4.3,1139,3.9,10100,"['Home Delivery', 'Indoor Seating', 'Table boo..."
27,Bakya Veg Restaurant,"20, Jaishankar Street, Near Ayodhya Mandapam,...",West Mambalam,"['South Indian', ' North Indian', ' Chinese']","['Panneer Butter Masala', ' Noodle', ' Chaat',...",400.0,4.2,457,4.0,19400,"['Breakfast', 'Home Delivery', 'Vegetarian Onl..."
28,Midnight Madness,"1\/1, F-3, 1st Floor, Sindhuja Complex, 29th ...",Adyar,['Italian'],"['Pasta', ' Noodle', ' Peri Peri Chicken Pizza']",450.0,4.1,625,3.3,10300,"['Home Delivery', 'Indoor Seating']"
29,Hotel Crescent,"309, Valluvar Kottam High Road, Nungambakkam,...",Nungambakkam,"['Chettinad', ' Chinese', ' North Indian', ' K...","['Chicken Grill', ' Shawarma', ' Paratha', ' F...",500.0,4.3,1030,4.2,2731,"['Home Delivery', 'Indoor Seating']"
30,Zaitoon,"35, Woods Road., Royapettah, Chennai",Royapettah,"['North Indian', ' Arabian', ' Chinese']","['Shawarma', ' Bbq Chicken', ' Biryani', ' Sal...",900.0,4.1,1118,4.1,2895,"['Home Delivery', 'Serves Halal', 'Free Parkin..."
31,Nithya Amirtham,"39, North Mada Street, Near Kapaleeswarar Tem...",Mylapore,"['South Indian', ' North Indian', ' Chinese']","['Tomato Soup', ' Filtered Coffee', ' Thali', ...",500.0,4.2,403,4.3,11100,"['Breakfast', 'Home Delivery', 'Vegetarian Onl..."
32,Shri Balaajee Bhavan,"412/07, Thoraipakam Road Over Bridge, Chromep...",Chromepet,"['South Indian', ' North Indian']","['Filtered Coffee', ' Panneer Butter Masala', ...",300.0,4.3,602,4.0,1868,"['Breakfast', 'Home Delivery', 'Vegetarian Onl..."
33,Kakada Ramprasad,"Ormes Road, Sylvan Lodge Colony, Kilpauk, Che...",Kilpauk,"['Mithai', ' Street Food', ' North Indian']","['Badam Milk', ' Chaat', ' Pav Bhaji', ' Jaleb...",450.0,4.3,455,4.3,4253,"['Breakfast', 'Home Delivery', 'Vegetarian Onl..."
34,Rasavid,"55 C, Velachery By-Pass Road, Sankaran Avenue...",Velachery,"['Andhra', ' Hyderabadi']","['Naan', ' Biryani', ' Bbq Fish', ' Tomato Sou...",800.0,3.9,350,3.4,3708,"['Home Delivery', 'Indoor Seating', 'Buffet']"
35,Buhari,"Near Vetri Theatre, Chromepet, Chennai",Chromepet,"['Biryani', ' Arabian', ' North Indian', ' Chi...","['Biryani', ' Chicken 65', ' Sea Food', ' Tea'...",800.0,3.5,646,3.8,1552,"['Home Delivery', 'Indoor Seating', 'Catering ..."
36,Domino's Pizza,"2, Ground Floor, Valavan Nagar, Kolathur, Che...",Kolathur,"['Pizza', ' Fast Food']","['Mexican Tacos', ' Peppy Paneer', ' Farmhouse...",400.0,4.0,429,4.1,5297,"['Home Delivery', 'Indoor Seating', 'Catering ..."
37,Shree Mithai,"18, Dr TV Road, Chetpet, Chennai",Chetpet,"['Mithai', ' Street Food', ' Fast Food']","['Chaat', ' Badam Milk', ' Pav Bhaji', ' Panip...",300.0,4.6,1085,4.4,18600,"['Breakfast', 'Home Delivery', 'Vegetarian Onl..."
38,New Andhra Meals Hotel,"6, Arcot Road, Valasaravakkam, Chennai",Valasaravakkam,"['Andhra', ' Chinese', ' South Indian', ' Nort...","['Paruppu Podi', ' Gongura Chicken', ' Panneer...",600.0,3.9,704,4.2,1457,"['Home Delivery', 'Indoor Seating', 'Table boo..."
39,Punjabi Nation,"15, GST Road, Guindy, Chennai",Guindy,"['North Indian', ' Chinese']","['Lassi', ' Roti', ' Naan', ' Butter Chicken',...",700.0,4.0,712,4.1,13600,"['Home Delivery', 'Indoor Seating']"
40,Krishna's Dosa Kadai,"40, Nolambur, Phase - 1, Mogappair, Chennai",Mogappair,"['South Indian', ' North Indian', ' Andhra', '...","['Pizza Dosa', ' Butter Naan', ' Coffee', ' Ch...",350.0,4.2,692,4.1,34600,"['Breakfast', 'Home Delivery', 'Vegetarian Onl..."
41,Al Sham,"1, Pillayar Koil Street, Near SRM University,...",Potheri,"['Chinese', ' North Indian', ' Kerala']","['Biryani', ' Chicken Grill', ' Tandoori Chick...",750.0,3.9,601,3.9,17500,"['Home Delivery', 'Table booking recommended',..."
42,Orange Wok,"11, 1st Floor, Khader Nawaz Khan Road, Nungam...",Nungambakkam,"['Malaysian', ' Asian', ' Chinese']","['Laksa', ' Dragon Chicken', ' Khau Suey', ' M...",1000.0,4.2,774,4.0,8705,"['Home Delivery', 'Free Parking', 'Indoor Seat..."
43,Ghuma Ghumalu,"1/398, Rajiv Gandhi Salai, OMR, Navalur, Chennai",Navallur,"['Chinese', ' South Indian', ' Biryani', ' And...","['Hyderabadi Biryani', ' Chicken 65', ' Chicke...",500.0,4.2,1059,3.6,5961,"['Home Delivery', 'Indoor Seating', 'Table res..."
44,KPS Ambur Biriyani,"6/20, Venugopal Street, Mogappair, Chennai",Mogappair,['Biryani'],"['Tandoori Chicken', ' Fried Rice Chicken', ' ...",250.0,3.6,409,3.7,11300,"['Home Delivery', 'Indoor Seating']"
45,Pedreno's,"113/114, PS Sivaswami Salai, Mylapore, Chennai",Mylapore,"['Pizza', ' American', ' Italian']","['Pizza', ' Gelato', ' Pasta', ' Coffee', ' St...",1200.0,4.3,946,4.0,787,"['Home Delivery', 'Desserts and Bakes', 'Live ..."
46,Madras Biryani,"105, EH Road, Sharma Nagar, Vyasarpadi, Peram...",Perambur,"['Biryani', ' Mughlai', ' Fast Food', ' South ...","['Egg Biryani', ' Chicken 65', ' Prawn', ' Fri...",400.0,4.0,559,3.8,15600,"['Home Delivery', 'Indoor Seating', 'Table Res..."
47,Palmshore,"99/59, Pantheon Road, Opposite Museum, Egmore...",Egmore,"['North Indian', ' Chinese', ' Arabian', ' BBQ...","['Mutton Mandi', ' Fish', ' Brownie', ' Sea Fo...",1000.0,4.4,2162,4.0,9721,"['Home Delivery', 'Indoor Seating', 'Table boo..."
48,Hotel Sri Vairam,"5/24, Karambakkam, Porur, Chennai",Porur,"['Biryani', ' South Indian', ' Chinese', ' Nor...","['Paratha', ' Biryani', ' Mutton Chukka', ' Ch...",300.0,4.0,523,3.8,14700,"['Home Delivery', 'Indoor Seating', 'Free Park..."
49,Sea Emperor,"11,12 & 13, Velachery Main Road, Ram Nagar, M...",Madipakkam,"['Chinese', ' Arabian', ' North Indian', ' Sea...","['Chicken Grill', ' Shawarma', ' Bbq Chicken',...",900.0,3.8,602,3.9,6855,"['Home Delivery', 'Indoor Seating', 'Catering ..."

##Q1) How many restaurants are in chennai for each type of cuisine?

In [55]:
import plotly.offline

fig = px.histogram(zomato_chndataset, x='Cuisine', color='Cuisine',
 title= 'No. of Restaurants by cuisine',
 labels={'Cuisine':'CUISINE'})
plotly.offline.plot(fig, filename='plot.html', auto_open=True)

'plot.html'

##Q2) Which are the Top 10 highest rated Seafood Restaurant in chennai?

In [24]:
seafood_df = zomato_chndataset[zomato_chndataset['Cuisine'].str.contains('Seafood')]
seafood_df.sort_values(by='Delivery Rating',ascending=False).head(10)

,Name of Restaurant,Address,Location,Cuisine,Top Dishes,Price for 2,Dining Rating,Dining Rating Count,Delivery Rating,Delivery Rating Count,Features
473,Dynasty,"315, Harrisons Hotel, Valluvar Kottam High Ro...","Harrisons Hotel, Nungambakkam","['Chinese', ' Seafood']","['Momos', ' Golden Fried Prawns', ' Fried Rice...",1200.0,4.2,337,4.6,779,"['Home Delivery', 'Full Bar Available', 'Valet..."
2910,Taj Thalapakattu Biriyani,"224, Trunk Road, Opposite, Panayathamman Koil...",Poonamalle,"['North Indian', ' Chinese', ' Seafood', ' Bev...",Invalid,600.0,3.4,42,4.4,831,"['Home Delivery', 'Indoor Seating']"
622,Hotel Runs,"104/13, Sardar Patel Road, Adyar, Chennai",Adyar,"['North Indian', ' Chinese', ' Seafood', ' Bir...","['Chicken Grill', ' Paratha', ' Chicken Curry'...",650.0,3.9,304,4.3,1386,"['Home Delivery', 'Indoor Seating']"
376,China Town,"74, 3rd Floor, Cathedral Road, Gopalapuram, C...",Gopalapuram,"['Chinese', ' Seafood']","['Momos', ' Dragon Chicken', ' Chicken Momo', ...",1200.0,4.1,468,4.3,637,"['Home Delivery', 'Table reservation required'..."
96,Urban Spatula,"Plot 1633, 54, H-Block, Ground Floor, 13th Ma...",Anna Nagar West,"['Continental', ' Seafood', ' Biryani', ' Ital...","['Burgers', ' Pasta', ' Fish', ' Fries', ' Chi...",800.0,4.4,794,4.3,911,"['Home Delivery', 'Free Parking', 'Table booki..."
903,Chidambaram New Moorthy Cafe,"1204, 6th Avenue, P Block, Anna Nagar West, C...",Anna Nagar West,"['North Indian', ' Seafood', ' Chinese']","['Paratha', ' Pepper Chicken', ' Lobster', ' E...",500.0,4.1,192,4.3,715,"['Home Delivery', 'Indoor Seating']"
195,The Marina,"39, College Road, Nungambakkam, Chennai",Nungambakkam,"['Seafood', ' North Indian', ' Chinese']","['Sea Food', ' Jumbo Prawns', ' Biryani', ' Fi...",1600.0,4.8,1082,4.3,373,"['Home Delivery', 'Indoor Seating', 'Table res..."
1398,Nite Bite,"386, Anna Salai, Saidapet, Chennai",Saidapet,"['Chinese', ' Seafood', ' North Indian', ' Bir...",['Biryani'],450.0,3.6,119,4.3,1429,"['Home Delivery', 'Indoor Seating', 'Wifi']"
14,Hotel Paramount,"12/5, Ormes Road, Kilpauk, Chennai",Kilpauk,"['North Indian', ' Chinese', ' Seafood', ' Sou...","['Biryani', ' Butter Chicken', ' Tandoori Chic...",500.0,4.3,1266,4.2,17700,"['Breakfast', 'Home Delivery', 'Indoor Seating..."
252,Pandia's Avenue,"114, SN Chetty Street, Kalmandapam, Royapuram...",Royapuram,"['North Indian', ' Chinese', ' Biryani', ' Sou...","['Faluda', ' Biryani', ' Paratha', ' Chicken 6...",750.0,4.0,419,4.2,6757,"['Home Delivery', 'Table booking recommended',..."

##Q3) Which is the best briyani in chennai?

In [25]:
Biryani_dataset = zomato_chndataset[zomato_chndataset['Cuisine'].str.contains('Biryani')]
Biryani_dataset.sort_values(by='Delivery Rating',ascending=False).head(3)

,Name of Restaurant,Address,Location,Cuisine,Top Dishes,Price for 2,Dining Rating,Dining Rating Count,Delivery Rating,Delivery Rating Count,Features
1985,Arabian Plate,"7/26, Sasthiri Nagar Main Road, Near Kakkan B...",Adambakkam,"['Arabian', ' Biryani']",Invalid,300.0,3.7,58,4.7,491,"['Home Delivery', 'Indoor Seating']"
3158,Biryani In A Box,"60/1, Halls Road, Egmore, Chennai",Egmore,"['Biryani', ' Fast Food']",Invalid,400.0,0.0,0,4.6,78,['Home Delivery']
8779,SS Hyderabad Biryani,"975, Ameer Complex, Near Kaladipet market, T....",Tiruvottiyur,"['Biryani', ' North Indian', ' Chinese', ' Ara...",Invalid,500.0,3.9,267,4.5,2307,"['Home Delivery', 'Catering Available', 'Indoo..."

#####Q4) Which places have the highest rated restaurant for each Cuisine in chennai?

In [26]:
highest_rated_dataset = zomato_chndataset[zomato_chndataset['Delivery Rating'] >= 4.5]
highest_rated_dataset

,Name of Restaurant,Address,Location,Cuisine,Top Dishes,Price for 2,Dining Rating,Dining Rating Count,Delivery Rating,Delivery Rating Count,Features
62,Amadora Gourmet Ice Cream & Sorbet,"23, Wallace Garden, 3rd Street, Nungambakkam,...",Nungambakkam,"['Desserts', ' Ice Cream']","['Sandwich', ' Gelato', ' Chocolate Icecreams'...",500.0,4.8,1516,4.5,361,"['Home Delivery', 'Outdoor Seating', 'Desserts..."
78,Shri Rajasthani Dhaba,"C 40, 3rd Floor, 2nd Avenue, Opposite KFC, An...",Anna Nagar West,"['Rajasthani', ' North Indian']","['Rajasthani Thali', ' Buttermilk', ' Roti', '...",500.0,4.5,983,4.5,5537,"['Home Delivery', 'Vegetarian Only', 'Indoor S..."
92,Fruit Shop On Greams Road,"11, Greams Road, Thousand Lights, Chennai",Thousand Lights,"['Beverages', ' Fast Food', ' Healthy Food', '...","['Fruit Juices', ' Sandwich', ' Mint Lime Cool...",350.0,4.5,609,4.6,1699,"['Home Delivery', 'Vegetarian Only', 'Indoor S..."
163,Momo Sa-Khang by Kailash Kitchen,"2/247, Perinbavilas Complex, Opposite Chitra ...",Choolaimedu,"['Momos', ' Chinese']","['Momos', ' Noodle', ' Chowmein', ' Fried Momo...",350.0,4.8,1658,4.5,2825,"['Home Delivery', 'Free Parking', 'Indoor Seat..."
164,La Chocolate,"5, Casa Major Road, Opposite Corporation Bank...",Egmore,"['Bakery', ' Desserts', ' Italian', ' Continen...","['Brownie', ' Red Velvet', ' Photo Cake', ' Ch...",800.0,4.0,256,4.5,1574,"['Home Delivery', 'Vegetarian Only', 'Free Par..."
...,...,...,...,...,...,...,...,...,...,...,...
11043,Kulfi Treat,"4, Kuppu Arcade, Venkat Narayana Road, T. Nag...",T. Nagar,"['Desserts', ' Ice Cream', ' Beverages']",Invalid,100.0,3.8,54,4.5,316,"['Home Delivery', 'Vegetarian Only', 'Indoor S..."
11179,Chennai Kulfi,"30, Ganapathy Rao Nagar, Kolathur, Chennai",Kolathur,"['Ice Cream', ' Desserts']",Invalid,150.0,2.8,20,4.5,177,"['Home Delivery', 'Vegetarian Only', 'Indoor S..."
11377,NIC - Natural Ice Creams,Delivery Only,Mylapore,['Ice Cream'],Invalid,150.0,0.0,0,4.5,145,"['Delivery Only', 'Desserts and Bakes']"
11379,NIC - Natural Ice Creams,"House 3, Kundrathur Main Road, M S Nagar, Por...",Porur,['Ice Cream'],Invalid,150.0,0.0,0,4.6,102,"['Delivery Only', 'Desserts and Bakes']"
11767,Green Crush,"114, Waitrose Supermarket, Luz Church Road, N...",Alwarpet,['Beverages'],Invalid,200.0,0.0,0,4.6,116,"['Home Delivery', 'Vegetarian Only']"

In [30]:
import plotly.offline


fig = px.histogram(highest_rated_dataset, x='Location', color='Cuisine',
 title= 'No. of Best Restaurant for each by Location').update_xaxes(categoryorder="total descending")
plotly.offline.plot(fig, filename='plot.html', auto_open=True)

'plot.html'

##Q5) What is the Avg Price Distibution of highest rated restaurant for each Cuisine Type in Mumbai?

In [31]:
highest_rated_dataset = highest_rated_dataset.groupby(by=['Location', 'Top Dishes'])['Price for 2'].mean().reset_index()
highest_rated_dataset.head()

     Location                                         Top Dishes  Price for 2
0  Adambakkam                                            Invalid        250.0
1       Adyar  ['Chocolava Cake', ' Pizza Burger', ' Mexican ...        400.0
2       Adyar  ['Cupcake', ' Sandwich', ' Bagel', ' Brownie',...        250.0
3    Alwarpet                                            Invalid        200.0
4    Alwarpet  ['Brownie', ' Hot Chocolate', ' Cheesecake', '...        500.0

In [33]:
import plotly.offline

fig = px.scatter(highest_rated_dataset, x="Location", y="Price for 2", color="Top Dishes", symbol="Top Dishes",
 title=' Avg Price Distibution of High rated restaurant for each Top Dishes')#.update_traces(marker_size=0)
plotly.offline.plot(fig, filename='plot.html', auto_open=True)

'plot.html'

##Q6) Which areas have a large number of Chinese Restaurant Market?

In [34]:
chinese_dataset = zomato_chndataset[zomato_chndataset['Cuisine'].str.contains('Chinese')]
chinese_dataset

,Name of Restaurant,Address,Location,Cuisine,Top Dishes,Price for 2,Dining Rating,Dining Rating Count,Delivery Rating,Delivery Rating Count,Features
2,SS Hyderabad Biryani,"98/339, Arcot Road, Opposite Gokulam Chit Fun...",Kodambakkam,"['Biryani', ' North Indian', ' Chinese', ' Ara...","['Brinjal Curry', ' Tandoori Chicken', ' Chick...",500.0,4.3,1361,4.4,10500,"['Home Delivery', 'Indoor Seating']"
4,Tasty Kitchen,"135B, SRP Colony, Peravallur, Near Perambur, ...",Perambur,"['Chinese', ' Biryani', ' North Indian', ' Che...","['Mutton Biryani', ' Chicken Rice', ' Tomato R...",450.0,4.2,617,4.1,22400,"['Home Delivery', 'Indoor Seating']"
5,Dine N Fun,"Opposite Forest Office, Tambaram Main Road, S...",Medavakkam,"['South Indian', ' North Indian', ' Chinese']","['Chicken Grill', ' Shawarma', ' Naan', ' Chic...",450.0,4.1,567,3.8,24700,"['Home Delivery', 'Indoor Seating']"
8,Savoury Sea Shell,"3, E Block, 3rd Avenue, Anna Nagar East, Chennai",Anna Nagar East,"['Arabian', ' Chinese', ' North Indian', ' Leb...","['Shawarma', ' Chicken Grill', ' Brownie', ' S...",1400.0,4.2,2564,4.1,21700,"['Home Delivery', 'Indoor Seating', 'Card Upon..."
9,Sangeetha Veg Restaurant,"102/82, GN Chetty Road, T. Nagar, Chennai",T. Nagar,"['South Indian', ' North Indian', ' Chinese', ...","['Filtered Coffee', ' Chaat', ' Faluda', ' Mas...",800.0,4.4,1578,4.2,39600,"['Breakfast', 'Home Delivery', 'Vegetarian Onl..."
...,...,...,...,...,...,...,...,...,...,...,...
12014,Bowl Bazaar,Delivery Only,Adyar,"['North Indian', ' South Indian', ' Chinese', ...",Invalid,500.0,0.0,0,0.0,0,['Delivery Only']
12015,Bowl Bazaar,Delivery Only,Medavakkam,"['North Indian', ' South Indian', ' Chinese', ...",Invalid,500.0,0.0,0,0.0,0,['Delivery Only']
12016,Bowl Bazaar,Delivery Only,Perungudi,"['North Indian', ' South Indian', ' Chinese']",Invalid,400.0,0.0,0,0.0,0,['Delivery Only']
12017,Bowl Bazaar,Delivery Only,Medavakkam,"['North Indian', ' South Indian', ' Chinese']",Invalid,400.0,0.0,0,0.0,0,['Delivery Only']
12018,Bowl Bazaar,Delivery Only,Ashok Nagar,"['North Indian', ' South Indian', ' Chinese']",Invalid,400.0,0.0,0,0.0,0,['Delivery Only']

In [35]:
chinese_rest_dataset = chinese_dataset.groupby(by='Location').agg({'Name of Restaurant' : 'count', 'Price for 2' : 'mean'}).rename(columns= {'Name of Restaurant' : 'COUNT OF RESTAURANTS'})
chinese_rest_dataset = chinese_rest_dataset.sort_values('COUNT OF RESTAURANTS', ascending=False).head(25)                                                                               
chinese_rest_dataset.head()

           COUNT OF RESTAURANTS  Price for 2
Location
Porur                       131   409.541985
Ambattur                    116   374.568966
Velachery                   102   488.235294
Perambur                     99   413.636364
Perungudi                    93   445.698925

In [36]:
# Assuming 'chinese_rest_df' is your DataFrame
import plotly.offline

chinese_rest_dataset.reset_index(inplace=True)  # Resetting the index to make 'REGION' a column
fig = px.bar(chinese_rest_dataset, x='Location', y='COUNT OF RESTAURANTS', color='Price for 2', title='No. of Chinese Restaurant by places')
plotly.offline.plot(fig, filename='plot.html', auto_open=True)

'plot.html'

##Q7) Is there a relation between Price and Rating by each Cuisine Type?

In [37]:
price_rating_dataset = zomato_chndataset.groupby(['Top Dishes', 'Dining Rating'])['Price for 2'].mean().reset_index()
price_rating_dataset

,Top Dishes,Dining Rating,Price for 2
0,Invalid,0.0,292.467583
1,Invalid,0.3,250.000000
2,Invalid,1.0,450.000000
3,Invalid,1.7,275.000000
4,Invalid,1.9,400.000000
...,...,...,...
2367,"['Wine', ' Sea Food', ' Gulab Jamun Cheesecake...",4.1,700.000000
2368,"['Wood Fire Pizza', ' Fries', ' Iced Tea', ' T...",3.3,600.000000
2369,['Wood Fire Pizza'],4.0,650.000000
2370,"['Yellow Rice', ' Fish', ' Butter Chicken', ' ...",3.7,800.000000
2371,['Zinger Burger'],4.0,500.000000

In [ ]:
 !pip install -U kaleido

In [38]:
import plotly.offline

fig = px.line(price_rating_dataset, y="Price for 2", x="Dining Rating",color='Top Dishes')
plotly.offline.plot(fig, filename='plot.html', auto_open=True)

'plot.html'

##Q8) Is there a relation between Region and Price?

In [39]:
region_price_dataset = zomato_chndataset.groupby(['Location'])['Price for 2'].mean().reset_index()
region_price_dataset

                                              Location  Price for 2
0     InterContinental Chennai Mahabalipuram Resort...  1500.000000
1                                        Abhiramapuram   228.571429
2                          Abu Sarovar Portico, Egmore  1000.000000
3                                           Adambakkam   291.025641
4                                                Adyar   443.550000
..                                                 ...          ...
263                              Vivira Mall, Navallur   500.000000
264                                       Washermenpet   291.735537
265             WelcomHotel, RK Salai (Cathedral Road)  2075.000000
266                                      West Mambalam   267.846154
267                     Zone by The Park, Pallikaranai  1633.333333

[268 rows x 2 columns]

In [40]:
import plotly.offline

fig = px.scatter(region_price_dataset, x="Location", y="Price for 2").update_traces(marker_size=5)
plotly.offline.plot(fig, filename='plot.html', auto_open=True)

'plot.html'

##Q9) Find the list of Affordable Restaurants?

In [41]:
max_price = zomato_chndataset['Price for 2'].max()
one_fourth_price = max_price/4
one_fourth_price

1250.0

In [42]:
# Finding list of restaurants that have price less than and equal to 1/4th of the max price i.e Finding Cheap Restauran
aff_rest_dataset = zomato_chndataset[['Name of Restaurant', 'Price for 2', 'Top Dishes', 'Location', 'Cuisine']]
aff_rest_dataset = aff_rest_dataset[aff_rest_dataset['Price for 2'] <= 1250]
aff_rest_dataset.sort_values(by='Price for 2', inplace=True)
aff_rest_dataset

,Name of Restaurant,Price for 2,Top Dishes,Location,Cuisine
4685,Soda Hub,40.0,Invalid,"OMR Food Street, Navallur",['Beverages']
6854,Planet Soda,50.0,Invalid,"OMR Food Street, Kandanchavadi","['Beverages', ' Juices']"
7405,Indian Coffee House,50.0,Invalid,Vepery,"['Beverages', ' Juices']"
8355,Kaafemaa,50.0,Invalid,Ambattur,['Beverages']
1448,Mamee Soup,60.0,"['Herbal Soup', ' French Onion Soup']",West Mambalam,['Healthy Food']
...,...,...,...,...,...
917,Fabcafe By Fabindia,1200.0,"['Momos', ' Galauti Kebab', ' Chaat', ' Cheese...",Besant Nagar,"['Cafe', ' North Indian', ' Biryani', ' Momos'..."
828,Food Exchange - Novotel Chennai Chamiers Road,1200.0,"['Fish', ' Sea Food', ' Noodle', ' Salad', ' C...","Novotel Chennai, Nandanam","['Continental', ' Italian', ' North Indian', '..."
165,Copper Chimney,1200.0,"['Paneer Tikka', ' Naan', ' Dal Makhani', ' Ru...",Gopalapuram,"['North Indian', ' Arabian', ' Biryani', ' Mug..."
1084,18 Degree North - Clarion Hotel,1200.0,"['Butter Chicken', ' Biryani', ' Dal Makhani',...","Clarion Hotel, Mylapore","['North Indian', ' Mughlai', ' Chettinad', ' D..."
1166,The Roof Top Lounge,1200.0,"['Lemon Cheesecake', ' Arabian Platter', ' Jum...","Ramada Plaza, Guindy","['BBQ', ' North Indian', ' Continental']"

In [43]:
# Finding the highest rated list of restaurants
highrate_rest_dataset = zomato_chndataset[['Name of Restaurant', 'Price for 2', 'Top Dishes', 'Location', 'Cuisine','Delivery Rating']]
highrate_rest_dataset = highrate_rest_dataset[highrate_rest_dataset['Delivery Rating'] >= 4.1]
highrate_rest_dataset.sort_values(by='Price for 2', inplace=True)
highrate_rest_dataset

,Name of Restaurant,Price for 2,Top Dishes,Location,Cuisine,Delivery Rating
1518,Lassi Junction,100.0,Invalid,Anna Nagar West,"['Beverages', ' Ice Cream']",4.1
5678,JM Pazhamudir Cholai,100.0,Invalid,Maduravoyal,['Beverages'],4.2
2855,Mo Square,100.0,Invalid,Anna Nagar East,['Momos'],4.3
2536,Juice Spot,100.0,Invalid,T. Nagar,['Beverages'],4.1
6039,Fruit Gallery Juice Shop,100.0,Invalid,Perambur,"['Beverages', ' Juices']",4.1
...,...,...,...,...,...,...
243,Asia Kitchen by Mainland China,1800.0,"['Dumplings', ' Mocktails', ' Fish', ' Treasur...","The Spring Hotel, Nungambakkam","['Momos', ' Asian', ' Chinese', ' Sushi']",4.1
102,Mainland China,1800.0,"['Noodle', ' Dumplings', ' Momos', ' Hakka Noo...","Phoenix Market City, Velachery","['Chinese', ' Asian', ' Sushi', ' Japanese', '...",4.2
234,Hamsa,1800.0,"['Gulab Jamun', ' Cheese Kurkuri', ' Tomato Sh...",Adyar,"['North Indian', ' Chettinad', ' Mughlai', ' D...",4.4
333,Teppan,2000.0,"['Sashimi', ' Nigiri Sushi', ' Maki Roll', ' S...",Alwarpet,['Japanese'],4.1
250,Benjarong,2000.0,"['Noodle', ' Tom Yum Soup', ' Fish', ' Lemongr...",Alwarpet,['Thai'],4.3

##Q10)Find the list of most Reliable Restaurants?

In [44]:
mean_votes = zomato_chndataset['Delivery Rating Count'].mean()
mean_votes

713.7197139768854

In [45]:
# Finding list of restaurants that have Votes greater than and equal to Mean of Vote
mean_rest_dataset = zomato_chndataset[['Name of Restaurant', 'Price for 2', 'Top Dishes', 'Location', 'Cuisine', 'Delivery Rating Count']]
mean_rest_dataset = mean_rest_dataset[mean_rest_dataset['Delivery Rating Count'] >713]
mean_rest_dataset.sort_values(by='Delivery Rating Count', inplace=True)
mean_rest_dataset

,Name of Restaurant,Price for 2,Top Dishes,Location,Cuisine,Delivery Rating Count
2146,Om Snacks,150.0,Invalid,Kodambakkam,"['Sandwich', ' Fast Food']",714
903,Chidambaram New Moorthy Cafe,500.0,"['Paratha', ' Pepper Chicken', ' Lobster', ' E...",Anna Nagar West,"['North Indian', ' Seafood', ' Chinese']",715
1955,Marhaba Family Restaurant,500.0,"['Tandoori Chicken', ' Dragon Chicken']",Kotturpuram,"['North Indian', ' Biryani', ' Chinese', ' Rol...",715
4240,Combo Biriyani House,400.0,Invalid,Tambaram,"['Biryani', ' North Indian', ' Chinese']",715
11240,UBQ by Barbeque Nation,500.0,Invalid,Velachery,"['North Indian', ' Biryani']",716
...,...,...,...,...,...,...
8822,Sangeetha Veg Restaurant,500.0,"['Coffee', ' Faluda', ' Pongal', ' Rava Dosa',...",Thuraipakkam,"['South Indian', ' North Indian', ' Chinese']",45500
232,Sapthagiri Tiffin Centre,150.0,"['Paratha', ' Noodle', ' Idli', ' Masala Dosa'...",T. Nagar,"['South Indian', ' Chinese']",47200
22,Supriya Andhra Restaurant,650.0,"['Biryani', ' Raita']",Thuraipakkam,"['Biryani', ' North Indian', ' Chinese']",50100
251,Hotelkaar Biriyani,350.0,"['Biryani', ' Chicken 65', ' Pepper Chicken', ...",T. Nagar,"['South Indian', ' Biryani']",51700
55,Guntur Gongura,500.0,"['Chicken Biryani', ' Vegetable Biryani', ' Hy...",Sholinganallur,"['Biryani', ' Andhra', ' North Indian', ' Chin...",59900

In [46]:
reliable_rest_dataset = pd.merge(mean_rest_dataset, highrate_rest_dataset, how='inner', on=['Name of Restaurant', 'Location'])
reliable_rest_dataset = reliable_rest_dataset[['Name of Restaurant', 'Price for 2_x', 'Top Dishes_x', 'Location', 'Cuisine_x']]
reliable_rest_dataset.rename(columns={'NAME':'Name of Restaurant', 'PRICE_x':'Price for 2', 'Top Dishes_x':'Top Dishes',
 'Location':'Location', 'Cuisine_x':'Cuisine'},inplace=True)

In [47]:
reliable_rest_dataset

,Name of Restaurant,Price for 2_x,Top Dishes,Location,Cuisine
0,Chidambaram New Moorthy Cafe,500.0,"['Paratha', ' Pepper Chicken', ' Lobster', ' E...",Anna Nagar West,"['North Indian', ' Seafood', ' Chinese']"
1,SS Hyderabad Biryani,500.0,Invalid,Ambattur,"['Biryani', ' North Indian', ' Chinese', ' Ara..."
2,SS Hyderabad Biryani,500.0,Invalid,Ambattur,"['Biryani', ' North Indian', ' Chinese', ' Ara..."
3,SS Hyderabad Biryani,500.0,Invalid,Ambattur,"['Biryani', ' North Indian', ' Chinese', ' Ara..."
4,Le Wrap Factorie,250.0,Invalid,Chetpet,"['American', ' Mexican', ' Fast Food']"
...,...,...,...,...,...
601,Sangeetha Veg Restaurant,650.0,"['Filtered Coffee', ' Pongal', ' Onion Rava Do...",Velachery,"['South Indian', ' North Indian', ' Chinese', ..."
602,Krishna's Dosa Kadai,350.0,"['Pizza Dosa', ' Butter Naan', ' Coffee', ' Ch...",Mogappair,"['South Indian', ' North Indian', ' Andhra', '..."
603,Sukkubhai Biriyani,1000.0,"['Beef Biryani', ' Beef Fry', ' Paratha', ' Pa...",Alandur,"['Biryani', ' North Indian', ' Mughlai', ' Des..."
604,Sangeetha Veg Restaurant,800.0,"['Filtered Coffee', ' Chaat', ' Faluda', ' Mas...",T. Nagar,"['South Indian', ' North Indian', ' Chinese', ..."
605,Sangeetha Veg Restaurant,500.0,"['Coffee', ' Faluda', ' Pongal', ' Rava Dosa',...",Thuraipakkam,"['South Indian', ' North Indian', ' Chinese']"